# Netlify Configuration

[build]
 command = "cd frontend && npm install --force && NODE_OPTIONS=--openssl-legacy-provider DISABLE_ESLINT_PLUGIN=true npm run build"
  publish = "frontend/build"

[functions]
  directory = "netlify/functions"
[build.environment]
  NODE_VERSION = "18"
